name: master_scanner_app
description: QR Code Scanner.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  base_core:
    path: packages/base_core

  dio: ^5.4.0
  get_it: ^7.6.7
  get: ^4.6.5
  chucker_flutter: ^1.6.3
  permission_handler: ^11.0.1
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1

  qr_flutter: ^4.0.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  easy_localization: ^3.0.3
  url_launcher: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  qr_code_scanner: ^1.0.1
  path: ^1.8.3
  simple_ripple_animation: ^0.0.9
  expandable_text: ^2.3.0
  package_info_plus: ^5.0.1
  widgets_to_image: ^0.0.2
  path_provider: ^2.1.2
  screenshot: ^2.3.0
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/static/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Bold.ttf