name: qr_code_scanner
description: QR Code Scanner.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  get_it: ^7.6.7
  chucker_flutter: ^1.6.3
#  permission_handler: ^11.0.1
  flutter_lints: ^2.0.0
  flutter_flavorizr: ^2.2.1

  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  pretty_qr_code: ^3.0.0
  easy_localization: ^3.0.3
  url_launcher: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  flutter_animate: ^4.2.0+1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.4.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/anim/
    - assets/fonts/
    - assets/i18n/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/open_sans/static/OpenSans-Light.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Regular.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Medium.ttf
        - asset: assets/fonts/open_sans/static/OpenSans-Bold.ttf